version: "3"

services:
  janusgraph:
    image: janusgraph/server:0.3.1
    container_name: janusgraph-0.3.1
    ports:
      - "8182:8182"
    volumes:
      - "janusgraph-data:/var/lib/janusgraph"

volumes:
  janusgraph-data:
