version: '2.1'
services:
  janusgraph:
    image: janusgraph/server:0.3.1
    container_name: janusgraph
    ports:
      - "8182:8182"
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: ["./bin/gremlin-server.sh", "./conf/gremlin-server/gremlin-server-berkeleyje-es.yaml"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: janusgraph-es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 30s
      retries: 30
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./docker/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml